<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimmingRootAssembly Include="DevDen" />
    <InvariantGlobalization>true</InvariantGlobalization>
    <BlazorEnableCompression>true</BlazorEnableCompression>
    <WasmEnableWebcil>true</WasmEnableWebcil>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.13" PrivateAssets="all" />
    <PackageReference Include="Markdig" Version="0.40.0" />
  </ItemGroup>
  <Target Name="BuildTailwind" BeforeTargets="BeforeBuild" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="npx tailwindcss@3 -i ./wwwroot/css/tailwind.input.css -o ./wwwroot/css/app.css --minify" ContinueOnError="true" />
  </Target>

</Project>